### ISSUE TITLE
question: How do I encrypt JWT (HS256) with secret in version 3

### ISSUE THREAD

**Issue by tombrouwer** [panva/jose#107]
Hi,

First, thanks to all the hard work!

Before in version 2 I used the following to encrypt with HS256:
```
JWT.sign(this.getPayload(), this.tokenSecret, {
      algorithm: this.algorithm,
      expiresIn: this.tokenTtl,
});
```

Where tokenSecret is a string, algorithm is "HS256" (string type) en tokenTtl is "60m" (string type). Now I have updated the package to version 3.

When I try:
```
new SignJWT(this.getPayload())
      .setProtectedHeader({ alg: this.algorithm })
      .setIssuedAt()
      .setIssuer("urn:example:issuer")
      .setAudience("urn:example:audience")
      .setExpirationTime(String(this.tokenTtl))
      .sign(crypto.createSecretKey(this.tokenSecret));
```

Typescript will tell me that tokenSecret (string) is not assignable to "ArrayBufferView". Can there be a simple example with signing with a secret key (string)?

Thanks in advance!

**Comment by panva** [comment]
Even without asking for a stack i can tell the problem is not with the types of this lib, but rather how you call node's [`crypto.createSecretKey`](https://nodejs.org/docs/latest-v14.x/api/crypto.html#crypto_crypto_createsecretkey_key).

> Can there be a simple example with signing with a secret key (string)?

Strings make terrible secrets, because they're assuming a readable encoding. I will not be opening the API to string key material inputs anymore.

`.sign` also [takes](https://github.com/panva/jose/blob/master/docs/types/_types_d_.keylike.md#type-alias-keylike) a Uint8Array for symmetric algorithms, in which case all you have to do is pass Buffer.from(secretString).
