### ISSUE TITLE
Module not found - Node version 14.15.1

### ISSUE THREAD

**Issue by AlexandreB27** [panva/jose#143]
Hello

I want to use your library, especially jwt part of your library. But, when I import jose/jwr/sign with ESM import, I have an error on module not found : 

Module not found: Error: Can't resolve 'jose/jwt/sign'

**To Reproduce**

I initialized an angular project and I ran `npm install jose@3`

Code to reproduce the behaviour:

```ts
import { Component } from '@angular/core';
import SignJWT from 'jose/jwt/sign'


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'metabase';

  constructor() {
    this.test();
  }

  public async test() {
    const secretKey = ''';

    var string = btoa(unescape(encodeURIComponent(secretKey))),
      charList = string.split(''),
      uintArray = [];
    for (var i = 0; i < charList.length; i++) {
      uintArray.push(charList[i].charCodeAt(0));
    }
    var key = new Uint8Array(uintArray);
    const jwt = await new SignJWT({ 'urn:example:claim': true })
      .setProtectedHeader({ alg: 'ES256' })
      .setIssuedAt()
      .setIssuer('urn:example:issuer')
      .setAudience('urn:example:audience')
      .setExpirationTime('2h')
      .sign(key)

  }

}

```

**Environment:**

- `jose` version: v3.5.1
- affected runtime is:  Node.js 14.15.1]

What I did wrong ?

**Comment by panva** [comment]
Whatever loader used by the stack you use to compile does not support subpath exports. This is not a bug in the library but a lack of node's module resolution support in your stack. You can resolve to directly import the specific dist file but it's not the regular way and you probably won't get types.

**Comment by panva** [comment]
@AlexandreB27 I've published an experimental version hoping to somehow support these left behind runtimes and loaders.

```sh
npm install jose@3.5.1-experimental
```

Instead of `import SignJWT from 'jose/jwt/sign'` do `import { SignJWT } from 'jose'.

Please come back to me with details whether that worked for you and definitely more details on what you use to compile the code you've posted above.

**Comment by tmmschmit** [comment]
@panva, Hello sorry to resurrect an old issue, I had the same problem  on a react app with the last version (3.11.1) but it's working well with `jose@3.5.1-experimental` :thinking:

**Comment by panva** [comment]
@tmmschmit I'm not going to be moving forward with a single root export module. Over time tooling ecosystems will pick up the [Subpath](https://nodejs.org/api/packages.html#packages_subpath_exports) [Conditional](https://nodejs.org/api/packages.html#packages_conditional_exports) schemas.

If your tooling doesn't support simply `import SignJWT from 'jose/jwt/sign'` then file an issue with said tooling for them to add this capability. Until then, you can find the actual dist file in your node modules and import from that as a workaround.

**Comment by LouisStAmour** [comment]
For folks looking for TypeScript support of export mapping in package.json, it's supposed to be in the next TypeScript release, 4.3 but no code has appeared yet. The tracking issue for support is at https://github.com/microsoft/TypeScript/issues/33079

For now, I'm doing things like the following:

```
// @ts-ignore
import { createRemoteJWKSet } from 'jose/dist/node/esm/jwks/remote';
// @ts-ignore
import { jwtVerify } from 'jose/dist/node/esm/jwk/verify';
```

Not great because of course, I don't get any type-checking. I've searched GitHub to see what others are doing and it looks like using `ts-node` instead of `tsc` directly is also an option, though I haven't tried it yet. One repo I saw actually copied all the types out of the module to add types that way, but that sounds like a pain. I had an idea that maybe I could make simple .d.ts files that referenced the existing types from the package, but even that seemed like too much work. I'll just wait for the next TS release in a month or two.
