### ISSUE TITLE
question: Node LTS version not supported?

### ISSUE THREAD

**Issue by MatteoJoliveau** [panva/jose#20]
Hello!
We are using Node 10 in production as we keep our applications on the oldest supported LTS available. By reading the package.json it seems the minimum required version is `11.8.0`.

Is there a specific reason behind this lock? Is it possibile by any chance to make the library available for Node 10 users as well?

Thank you

**Comment by panva** [comment]
Hi @MatteoJoliveau

> By reading the package.json it seems the minimum required version is 11.8.0.

> Is there a specific reason behind this lock? Is it possibile by any chance to make the library available for Node 10 users as well?

The readme explains this as well. The reason is KeyObject API which is only available starting with 11.6.0 and some important fixes to it in 11.8.0. 

I aim to release 1.0.0 stable API release with the rollout of node 12 end of April. 

These new APIs improve the sign/verify performance and reduce the need for dependencies. There’s also a new node API only coming out in 12.0.0 which brings EdDSA algorithm support. 

I am well aware that so far this library’s node requirements gates it from most users, that’s fine. Node 12 will be LTS eventually in October. And its still a stable release by all means. Getting the same security fix treatment as lts branches. 

That being said if these node features got backported to node lts/dubnium there’s no reason to keep this node requirement but so far noone’s requested them be backported. 

It’s really just that the crypto module didn’t have the improved APIs my jose relies upon.

**Comment by panva** [comment]
I've made @panva/jose compatible with lts/dubnium, it is now being tested with Node.js `^10.13.0 || >=12.0.0` and Electron `^6.0.0`

It is not without caveats, but they are acceptable.
- Importing X.509 certificates and handling x5c is only supported when Node.js >= 12.0.0 runtime is detected
- OKP keys are only supported when Node.js >= 12.0.0 runtime is detected
