### ISSUE TITLE
Maybe slightly tweak the exports?

### ISSUE THREAD

**Issue by nulltoken** [panva/jose#617]
### What happened?

While working on building an esm/cjs library, I happened to check the dependencies I'm relying on.

It looks like `jose` might benefit from some potential improvements:

 => https://publint.dev/jose@5.1.3

![image](https://github.com/panva/jose/assets/92363/d1ed98ec-eedc-44aa-a492-904b464c2c24)

![image](https://github.com/panva/jose/assets/92363/cd4a1e8e-f142-4200-b626-65e1bef6c79c)

 => https://arethetypeswrong.github.io/?p=jose%405.1.3

![image](https://github.com/panva/jose/assets/92363/704d672b-8ac7-4efe-8243-77051a6cf215)

Nothing critical in my case, but I thought you might want to know.

Cheers!

### Version

5.1.3

### Runtime

Node.js

### Runtime Details

Multiple

### Code to reproduce

```js
See above
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
I don't really know what I'm looking at, but messing around with conditional exports, especially the type ones has historically caused people pain. So i'm not going to touch anything unless there's an actual problem. I'm happy with the setup atm because

- it works for all the cases I've tried
- the type files are only included in the bundle once

The latter is important to me and with that the suggestion provided by the tool is not applicable here.

**Comment by nulltoken** [comment]
Thanks for the feedback!

:wave:

**Comment by nulltoken** [comment]
>I don't really know what I'm looking at

FWIW the provided pointers display links to a LOT of information about the "findings" and the underlying whys.

**Comment by panva** [comment]
Yeah, I appreciate the links to these tools, they seem really helpful.
