### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by josubg** [panva/jose#72]
**Describe the bug**
I get  TypeError: getCurves is not a function

**To Reproduce**

Steps to reproduce the behaviour:

1.  Install Jose
2.  Import: 
> import {JWT}  from "jose";
3. npm run start

```
**Expected behaviour**
Not crash

**Environment:**
 - `jose` version: 1.24.0
 - node version: 13.9.0

**Additional context**
Add any other context about the problem here.

 - [x ] the bug is happening on latest `jose` too.
 - [x ] i have searched the issues tracker on github for similar issues and couldn't find anything related. 
The nearest I found is:
[]( https://stackoverflow.com/questions/59871686/crypto-getcurves-is-undefined)

**Comment by panva** [comment]
The fact that you're doing `import` means that you transpile your dependencies. Stop doing so and you'll be fine, its likely that even node's `crypto` is polyfilled for you which is why you get the error.

```
❯ node -v                                                     
v13.9.0

❯ node -e 'const { JWT } = require("jose"); console.log(JWT)'
{
  decode: [Function (anonymous)],
  sign: [Function (anonymous)],
  verify: [Function (anonymous)],
  IdToken: { verify: [Function: verify] },
  LogoutToken: { verify: [Function: verify] },
  AccessToken: { verify: [Function: verify] }
}
```

The test suite is currently running for Node 10, 11, 12, 13 and electron 6, 7, and 8. 

https://nodejs.org/api/crypto.html#crypto_crypto_getcurves there's no reason for this not to be present.

**Comment by panva** [comment]
A quick note, i've release a new major (v3.x) which is now a universal module with 0 dependencies and now works the same in the browser as well as node.
